# Shopping Trends Data Analysis
**Objective:** Learn Python basics and perform basic data exploration and cleaning using Pandas.

**Steps:**
1. Load a CSV dataset into a Pandas DataFrame.
2. Explore data (head/tail, shape, columns, data types).
3. Handle missing values (identify, fill/drop).
4. Perform basic operations (filter rows, select columns).
5. Remove duplicates.
6. Create a derived column (`total_amount` = price * quantity).
7. Save the cleaned dataset as a new CSV file.

### Download the Dataset
Ensure you have downloaded the dataset from Kaggle: [Shopping Trends Dataset](https://www.kaggle.com/datasets/anvitkumar/shopping-dataset)
Place the `shopping_trends.csv` file in the same directory as this notebook.

In [1]:
import pandas as pd
import numpy as np
import os

### 1. Load Dataset

In [2]:
file_path = 'shopping_trends.csv'

if os.path.exists(file_path):
    df = pd.read_csv(file_path)
    print('Dataset loaded successfully!')
else:
    print(f'Error: {file_path} not found. Please download it and place it in the same directory.')
    # Fallback to mock data for demonstration if file is missing
    print('\nUsing mock data for demonstration purposes...')
    data = {
        'Customer ID': [1, 2, 3, 4, 5, 5], 
        'Age': [25, np.nan, 35, 45, 22, 22], 
        'Item Purchased': ['Sweater', 'Jeans', 'Sneakers', 'Hat', 'Sweater', 'Sweater'],
        'Purchase Amount (USD)': [50, 80, 120, 15, 50, 50],
        'Quantity': [1, 2, 1, 3, 1, 1]
    }
    df = pd.DataFrame(data)

Error: shopping_trends.csv not found. Please download it and place it in the same directory.

Using mock data for demonstration purposes...

### 2. Explore Data

In [3]:
print("\n--- FIRST 5 ROWS ---")
display(df.head())

print("\n--- LAST 5 ROWS ---")
display(df.tail())

print("\n--- DATASET SHAPE ---")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

print("\n--- COLUMN NAMES ---")
print(list(df.columns))

print("\n--- DATA TYPES ---")
print(df.dtypes)

print("\n--- DATASET INFO ---")
df.info()

--- FIRST 5 ROWS ---

   Customer ID   Age Item Purchased  Purchase Amount (USD)  Quantity
0            1  25.0        Sweater                     50         1
1            2   NaN          Jeans                     80         2
2            3  35.0       Sneakers                    120         1
3            4  45.0            Hat                     15         3
4            5  22.0        Sweater                     50         1

--- LAST 5 ROWS ---

   Customer ID   Age Item Purchased  Purchase Amount (USD)  Quantity
1            2   NaN          Jeans                     80         2
2            3  35.0       Sneakers                    120         1
3            4  45.0            Hat                     15         3
4            5  22.0        Sweater                     50         1
5            5  22.0        Sweater                     50         1

--- DATASET SHAPE ---
Rows: 6, Columns: 5

--- COLUMN NAMES ---
['Customer ID', 'Age', 'Item Purchased', 'Purchase Amount (USD)', 'Quantity']

--- DATA TYPES ---
Customer ID                int64
Age                      float64
Item Purchased               str
Purchase Amount (USD)      int64
Quantity                   int64
dtype: object

--- DATASET INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer ID            6 non-null      int64
 1   Age                    5 non-null      float64
 2   Item Purchased         6 non-null      str
 3   Purchase Amount (USD)  6 non-null      int64
 4   Quantity               6 non-null      int64
dtypes: float64(1), int64(3), str(1)
memory usage: 372.0 bytes

### 3. Handle Missing Values

In [4]:
print("--- MISSING VALUES BEFORE CLEANING ---")
print(df.isnull().sum())

# Fill numerical columns with mean
numeric_cols = df.select_dtypes(include=np.number).columns
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())

# Fill categorical columns with mode
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
for col in categorical_cols:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

print("\n--- MISSING VALUES AFTER CLEANING ---")
print(df.isnull().sum())

--- MISSING VALUES BEFORE CLEANING ---
Customer ID              0
Age                      1
Item Purchased           0
Purchase Amount (USD)    0
Quantity                 0
dtype: int64

--- MISSING VALUES AFTER CLEANING ---
Customer ID              0
Age                      0
Item Purchased           0
Purchase Amount (USD)    0
Quantity                 0
dtype: int64

C:\Users\satish\AppData\Local\Temp\ipykernel_11252\1873487784.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include=['object', 'category']).columns

### 4. Basic Operations

In [5]:
# Select Columns
print("--- SELECTED COLUMNS (Customer ID, Age, Item Purchased) ---")
selected_data = df[['Customer ID', 'Age', 'Item Purchased']]
display(selected_data.head())

# Filter Rows
print("\n--- CUSTOMERS AGE > 30 ---")
filtered_data = df[df['Age'] > 30]
display(filtered_data.head())

--- SELECTED COLUMNS (Customer ID, Age, Item Purchased) ---

   Customer ID   Age Item Purchased
0            1  25.0        Sweater
1            2  29.8          Jeans
2            3  35.0       Sneakers
3            4  45.0            Hat
4            5  22.0        Sweater

--- CUSTOMERS AGE > 30 ---

   Customer ID   Age Item Purchased  Purchase Amount (USD)  Quantity
2            3  35.0       Sneakers                    120         1
3            4  45.0            Hat                     15         3

### 5. Remove Duplicates

In [6]:
print(f"ROWS BEFORE REMOVING DUPLICATES: {len(df)}")
df = df.drop_duplicates()
print(f"ROWS AFTER REMOVING DUPLICATES: {len(df)}")

ROWS BEFORE REMOVING DUPLICATES: 6
ROWS AFTER REMOVING DUPLICATES: 5

### 6. Create Derived Column

In [7]:
# If 'Quantity' doesn't exist in the actual dataset, create it for demonstration
if 'Quantity' not in df.columns:
    df['Quantity'] = 1  

# Create total_amount
df['total_amount'] = df['Purchase Amount (USD)'] * df['Quantity']

print("--- DERIVED COLUMN CREATED ---")
display(df[['Purchase Amount (USD)', 'Quantity', 'total_amount']].head())

print("\n--- SUMMARY STATISTICS ---")
display(df.describe())

print("\nTOTAL CUSTOMERS:", df['Customer ID'].nunique())
print("TOTAL SALES (USD): $", df['total_amount'].sum())

--- DERIVED COLUMN CREATED ---

   Purchase Amount (USD)  Quantity  total_amount
0                     50         1            50
1                     80         2           160
2                    120         1           120
3                     15         3            45
4                     50         1            50

--- SUMMARY STATISTICS ---

       Customer ID        Age  Purchase Amount (USD)  Quantity  total_amount
count     5.000000   5.000000               5.000000  5.000000      5.000000
mean      3.000000  31.360000              63.000000  1.600000     85.000000
std       1.581139   9.080088              39.306488  0.894427     52.201533
min       1.000000  22.000000              15.000000  1.000000     45.000000
25%       2.000000  25.000000              50.000000  1.000000     50.000000
50%       3.000000  29.800000              50.000000  1.000000     50.000000
75%       4.000000  35.000000              80.000000  2.000000    120.000000
max       5.000000  45.000000             120.000000  3.000000    160.000000

TOTAL CUSTOMERS: 5
TOTAL SALES (USD): $ 425

### 7. Save Cleaned Dataset & Summary

In [8]:
# Save to CSV
cleaned_file_path = "cleaned_shopping_dataset.csv"
df.to_csv(cleaned_file_path, index=False)
print(f"CLEANED DATASET SAVED AS '{cleaned_file_path}'")

# Final Project Summary
print("\n" + "="*50)
print("PROJECT SUMMARY")
print("="*50)
print("""
1. Loaded the Shopping Trends dataset.
2. Explored data using head(), tail(), shape, columns, and data types.
3. Checked and handled missing values.
4. Performed filtering and column selection.
5. Removed duplicate records.
6. Created a derived column: total_amount.
7. Generated summary statistics.
8. Saved the cleaned dataset as cleaned_shopping_dataset.csv.
""")

CLEANED DATASET SAVED AS 'cleaned_shopping_dataset.csv'

==================================================
PROJECT SUMMARY
==================================================

1. Loaded the Shopping Trends dataset.
2. Explored data using head(), tail(), shape, columns, and data types.
3. Checked and handled missing values.
4. Performed filtering and column selection.
5. Removed duplicate records.
6. Created a derived column: total_amount.
7. Generated summary statistics.
8. Saved the cleaned dataset as cleaned_shopping_dataset.csv.